"""changed the column fullname to username and removed the constraint unique from it

Revision ID: f67208b7eb38
Revises: 306bcc762e5f
Create Date: 2026-06-22 02:37:34.831930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f67208b7eb38'
down_revision: Union[str, Sequence[str], None] = '306bcc762e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint(op.f('users_fullname_key'), 'users', type_='unique')
    op.drop_column('users', 'fullname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_fullname_key'), 'users', ['fullname'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
